// GLSL version to use
#version 460

// size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

// descriptor bindings for the pipeline
layout(rgba16f,set = 0, binding = 0) uniform image2D image;

struct Sphere {
    vec3 center;
    float radius;
};

struct Ray {
    vec3 origin;
    vec3 direction;
};

// camera space axis push constant block
layout( push_constant ) uniform constants
{
    vec4 position;
    vec4 front;
    vec4 up;
    vec4 right;
} CameraPushConstant;

float mapScene(vec3 p);

float sphereDistance(vec3 p, float s);

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);

    vec4 color = vec4(1.0, 1.0, 1.0, 1.0);

    // screen NDC
    float uv_x = ( 2.0 * texelCoord.x - size.x ) / size.x;
    float uv_y = ( 2.0 * texelCoord.y - size.y ) / size.x;

    // camera setup
    vec3 cameraPosition = CameraPushConstant.position.xyz;
    vec3 cameraForward = CameraPushConstant.front.xyz;
    vec3 cameraUp = CameraPushConstant.up.xyz;
    vec3 cameraRight = CameraPushConstant.right.xyz;

    // ray setup
    Ray ray;
    ray.origin = cameraPosition;
    ray.direction = normalize(uv_x * cameraRight + uv_y * cameraUp + cameraForward);

    // traveled distance
    float t = 0;

    // ray marching
    for(int i = 0; i < 80; i++) {
        vec3 p = ray.origin + ray.direction*t; // position along the ray
        float d = mapScene(p);
        t += d;

        if(d < .001) // early stop with hit threshold
            color = vec4(1.0, 0.0, 0.0, 1.0);
        if(t > 100.0) break; // early stop with max distance traveled threshold
    }

    imageStore(image, texelCoord, color);

    // color writing
}

float mapScene(vec3 p) 
{
    // sphere setup
    Sphere sphere;
    sphere.center = vec3(0,0,3);
    sphere.radius = 1.0;

    float distanceToSphere = sphereDistance(p - sphere.center, sphere.radius);

    return distanceToSphere;
}

float sphereDistance(vec3 p, float s)
{
    return length(p) - s;
}